export const DELIVERY_RESTAURANTS = [
  'The Rustic Plate',
  'Blue Ocean Grill',
  'Fireside Tavern',
  'SpiceMasters Kitchen',
  'Gourmet Grove',
  'Golden Harvest Cafe',
  'Urban Palate',
  'Sweet Serenity Bistro',
  'Farmhouse Flavors',
  'FusionFare Eatery',
  'Sizzle & Spice Grill',
  'Coastal Catch Seafood',
  'Bella Italia Trattoria',
  'Whispering Pines Pub',
  'ExoticEats Restaurant',
  'Streetwise Bites',
  'The Culinary Canvas',
  'Red Chili Cantina',
  'Moonlight Cafe',
  'Mediterranean Delights',
  'Thai Orchid Cuisine',
  'Crispy Crust Pizzeria',
  'Citrus Splash Cafe',
  'Harvest Moon Bistro',
  'Tasty Trails Diner',
  'Harborview Grill',
  'Soulful Sips Lounge',
  'SpiceFusion Express',
  'Urban Spicebox',
  'SpiceRoute Bistro',
  'The Hungry Artist',
  'Urban Farm Table',
  'SeaSalt Breeze',
  'Flavorful Journeys',
  'Fireside Elegance',
  'Farm Fresh Feasts',
  'AsiaPacific Bites',
  'Casa de Sabor',
  'Symphony Sweets',
  'Spice & Bloom Bistro',
  'Coastal Comfort Kitchen',
  'The Epicurean Palette',
  'Bayside Breeze Cafe',
  'Savory Secrets Tavern',
  'Leafy Greens Grill',
  'FlavorVista Kitchen',
  'Urban Tastebuds',
  'FusionFlame Fare',
  'SpiceCraft Deli',
  'BellaSera Trattoria',
]
