export enum DE_ScreenTypes {
  MENU = 'MENU',
  MENU_ITEM = 'MENU_ITEM',
  CONFIRM_ORDER = 'CONFIRM_ORDER',
  ORDER_PROGRESS = 'ORDER_PROGRESS',
  DELIVERY_GAME = 'DELIVERY_GAME',
  DELIVERY_GAME_RESULTS = 'DELIVERY_GAME_RESULTS',
  START_DELIVERY_GAME = 'START_DELIVERY_GAME',
}
